version: '3.9'

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:7010:5432"

volumes:
  postgres: 